#!/bin/bash


STATE=$(mocp -Q %state)

case $BLOCK_BUTTON in
    1) case "$STATE" in # left click
             "PAUSE") notify-send "mocp paused" ;;
             "PLAY") notify-send "Current tack
                Artist: `mocp -Q %artist`
                Album: `mocp -Q %album`
                Title: `mocp -Q %song`";;
             "STOP") notify-send "Music is stopped";;
        esac;;
    3) case "$STATE" in # right click
             "PAUSE" | "PLAY") mocp -G;;
             "STOP") xfce4-terminal -x mocp -m & ;;
        esac;;
    #scroll up for next song
    4) mocp -f;;
    #scroll down for previous song
    5) mocp -r;;
esac


case "$STATE" in

        "STOP") echo " Start moc" ;;
        "PAUSE") echo " `mocp -Q %song` - paused" ;;
        "PLAY") echo " `mocp -Q %song` `mocp -Q %ct`/`mocp -Q %tt`" ;;
esac

